<p></p><img src="https://i.pinimg.com/originals/59/8e/c4/598ec42e15c85716c6954c26840d4f4b.jpg" style="width: 100px"/>
<a href="https://github.com/sqrt495?tab=repositories" target="_parent">
    <h4><center><font color=black>Open In GitHub</font></center></h4></a>
<p></p>

## <center>[Run official tutorial!](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html)</center>

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
x

tensor([[8.4490e-39, 1.0102e-38, 9.0919e-39],
        [1.0102e-38, 8.9082e-39, 8.4489e-39],
        [9.6429e-39, 8.4490e-39, 9.6429e-39],
        [9.2755e-39, 1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39, 8.4490e-39]])

In [3]:
y = torch.rand(5, 3)
y

tensor([[0.8910, 0.8494, 0.2816],
        [0.1851, 0.0401, 0.2466],
        [0.6888, 0.3604, 0.8478],
        [0.3897, 0.9330, 0.2192],
        [0.6662, 0.4002, 0.3102]])

In [4]:
z = torch.add(x, y)
z

tensor([[0.8910, 0.8494, 0.2816],
        [0.1851, 0.0401, 0.2466],
        [0.6888, 0.3604, 0.8478],
        [0.3897, 0.9330, 0.2192],
        [0.6662, 0.4002, 0.3102]])

In [5]:
torch.add(z, y)

tensor([[1.7820, 1.6988, 0.5632],
        [0.3703, 0.0802, 0.4932],
        [1.3776, 0.7208, 1.6957],
        [0.7793, 1.8660, 0.4383],
        [1.3325, 0.8005, 0.6204]])

Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [6]:
z.t_()
z

tensor([[0.8910, 0.1851, 0.6888, 0.3897, 0.6662],
        [0.8494, 0.0401, 0.3604, 0.9330, 0.4002],
        [0.2816, 0.2466, 0.8478, 0.2192, 0.3102]])

In [7]:
z.size()

torch.Size([3, 5])

In [8]:
z[:, -1]

tensor([0.6662, 0.4002, 0.3102])

**Resizing**: If you want to resize/reshape tensor, you can use `torch.view`:

In [9]:
a = torch.randn(4, 4)
b = a.view(16)
c = a.view(-1, 8)  # the size -1 is inferred from other dimensions
print(a.size(), b.size(), c.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [10]:
a,b,c

(tensor([[ 1.5115, -0.8946, -1.4595,  2.0459],
         [ 1.1347, -1.7031, -0.0294, -0.9741],
         [ 2.2535, -1.1792, -0.1666,  1.5211],
         [ 1.4869, -0.5440, -0.4921,  0.1435]]),
 tensor([ 1.5115, -0.8946, -1.4595,  2.0459,  1.1347, -1.7031, -0.0294, -0.9741,
          2.2535, -1.1792, -0.1666,  1.5211,  1.4869, -0.5440, -0.4921,  0.1435]),
 tensor([[ 1.5115, -0.8946, -1.4595,  2.0459,  1.1347, -1.7031, -0.0294, -0.9741],
         [ 2.2535, -1.1792, -0.1666,  1.5211,  1.4869, -0.5440, -0.4921,  0.1435]]))

In [11]:
a[2,3].item(), type(a[2,3].item())

(1.5211070775985718, float)

Create a tensor and set `requires_grad=True` to track computation with it

In [12]:
y = torch.rand(5, 3, requires_grad=True)
y

tensor([[0.8462, 0.9030, 0.0357],
        [0.0618, 0.1346, 0.3981],
        [0.1742, 0.7052, 0.8535],
        [0.9533, 0.8688, 0.4496],
        [0.5946, 0.0776, 0.6057]], requires_grad=True)

In [13]:
torch.add(z.t_(), y)
y

tensor([[0.8462, 0.9030, 0.0357],
        [0.0618, 0.1346, 0.3981],
        [0.1742, 0.7052, 0.8535],
        [0.9533, 0.8688, 0.4496],
        [0.5946, 0.0776, 0.6057]], requires_grad=True)

In [14]:
y = y+8
y

tensor([[8.8462, 8.9030, 8.0357],
        [8.0618, 8.1346, 8.3981],
        [8.1742, 8.7052, 8.8535],
        [8.9533, 8.8688, 8.4496],
        [8.5946, 8.0776, 8.6057]], grad_fn=<AddBackward0>)

In [21]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

y

tensor([-960.1129, 1121.4379, -375.8685], grad_fn=<MulBackward0>)

Now in this case `y` is no longer a scalar. `torch.autograd` could not compute the full Jacobian directly, but if we just want the [vector-Jacobian](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0_%D0%AF%D0%BA%D0%BE%D0%B1%D0%B8) product, simply pass the vector to backward as argument:

In [22]:
v = torch.tensor([0.5, 1.0, 0.5], dtype=torch.float)
y.backward(v)

x.grad

tensor([1024., 2048., 1024.])

Neural networks can be constructed using the `torch.nn` package.

A typical training procedure for a neural network is as follows:

1. Define the neural network that has some learnable parameters (or weights)
2. Iterate over a dataset of inputs
3. Process input through the network
4. Compute the loss (how far is the output from being correct)
5. Propagate gradients back into the network’s parameters
6. Update the weights of the network, typically using a simple update rule: `weight = weight - learning_rate * gradient`

In [24]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
net

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

You just have to define the `forward` function, and the `backward` function (where gradients are computed) is automatically defined for you using `autograd`. You can use any of the Tensor operations in the `forward` function.

In [26]:
params = list(net.parameters())
print(len(params))
for _ in params:
    print(_.size())

10
torch.Size([6, 1, 3, 3])
torch.Size([6])
torch.Size([16, 6, 3, 3])
torch.Size([16])
torch.Size([120, 576])
torch.Size([120])
torch.Size([84, 120])
torch.Size([84])
torch.Size([10, 84])
torch.Size([10])


In [27]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0662, -0.0548,  0.1307, -0.1247, -0.0253, -0.0262,  0.0401,  0.0819,
         -0.0079,  0.0883]], grad_fn=<AddmmBackward>)


In [28]:
net.zero_grad()
out.backward(torch.randn(1, 10))

`torch.nn` only supports mini-batches. The entire `torch.nn` package only supports inputs that are a mini-batch of samples, and not a single sample.

For example, `nn.Conv2d` will take in a 4D Tensor of `nSamples x nChannels x Height x Width`.

If you have a single sample, just use `input.unsqueeze(0)` to add a fake batch dimension.

[READ MORE](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#define-the-network)